execute pathogen#infect()

colorscheme desert

" Hack NerdFont Complete Mono
" https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack
set guifont=HackNerdFontCompleteM-Regular:h18

set nowrap
set number
set noerrorbells visualbell

" tabs to spaces
set tabstop=2
set shiftwidth=2
set expandtab

" fzf plugin
set rtp+=/usr/local/opt/fzf

source ~/.vim/file_types.vim
source ~/.vim/mapping.vim
source ~/.vim/swap_files.vim
source ~/.vim/ack_search.vim

syntax region hereDocDashSQL matchgroup=Statement start=+<<\s*[-'\\]\?\z(SQLDOC\)+ end=+^\s*\z1+ contains=@SQL
      \ containedin=@shCaseList,shCommandSubList,shFunctionList
" Introduce ^^^^ the new heredoc to $VIMRUNTIME/syntax/sh.vim

" Start NERDTree
autocmd VimEnter * NERDTree
" and put the cursor back in the other window.
" autocmd VimEnter * NERDTree | wincmd p
