#!/bin/bash
set -e

repo=$(gh repo view --json nameWithOwner -q ".nameWithOwner")
ralphlabel="ralph"
username=$1

issuenum=$(gh api graphql -f query='
  query($q: String!) {
    search(query: $q, type: ISSUE, first: 100) {
      nodes {
        ... on Issue {
          number
          title
          url
          blockedBy(first: 20) { nodes { state } }
        }
      }
    }
  }' -f q="repo:$repo is:issue is:open assignee:$username label:$ralphlabel" \
  | jq '.data.search.nodes[] | select([.blockedBy.nodes[] | select(.state == "OPEN")] | length == 0) | .number'
)

echo $issuenum
