#!/bin/bash
set -e

CREDENTIALS=$(security find-generic-password -s "Claude Code-credentials" -w)
CLAUDE_PATH=${CLAUDE_CONFIG_DIR:-"~/.claude/"}
CONFIG_FILE="$CLAUDE_PATH/credentials.json"

echo "$CREDENTIALS" > $CONFIG_FILE

exit 0
