#! /bin/zsh

# ruby / rails / bundler config
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3)"
eval "$(rbenv init -)"

# node env config
eval "$(nodenv init -)"

# load yvm
export YVM_DIR=/usr/local/opt/yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh

# export PORT=3000
export REACT_APP_PORT=3001
export REACT_APP_API_ROOT=http://localhost:3000
export RAILS_ENV=development
export NODE_ENV=development
export LOCALSTACK_AUTH_TOKEN="ls-zoTo3875-TahU-KIpA-SUcu-modOXIZie9dc"
export GOPATH=$HOME/go
