#! /bin/zsh

ZSH_FOLDER=`dirname "$0"`
ROOT_FOLDER=$ZSH_FOLDER/..

source $ZSH_FOLDER/code_config
source $ZSH_FOLDER/exa_config
source $ZSH_FOLDER/prompt_config

source $ROOT_FOLDER/private/gitup/gitup.sh
source $ROOT_FOLDER/private/rbear/rbear.sh

export TERM=xterm-color
export CLICOLOR=1
export LSCOLORS=Dxfxcxdxbxegedabagacad

export EDITOR=mvim
export CC=/usr/bin/gcc

export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export LDFLAGS="-L/usr/local/opt/icu4c/lib"
export CPPFLAGS="-I/usr/local/opt/icu4c/include"
export PKG_CONFIG_PATH="/usr/local/opt/icu4c/lib/pkgconfig"

export PORT=3000
